# Generated by Django 6.0.4 on 2026-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_size', models.CharField(choices=[('solo', 'Solo'), ('2-10', '2–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('200+', '200+')], max_length=20)),
                ('industry', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under $5k'), ('5k_15k', '$5k – $15k'), ('15k_50k', '$15k – $50k'), ('50k_plus', '$50k+'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(choices=[('asap', 'ASAP'), ('1_3_months', '1–3 months'), ('3_6_months', '3–6 months'), ('flexible', 'Flexible')], max_length=20)),
                ('how_heard_about_us', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
