[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py create_superuser_if_none && daphne -b 0.0.0.0 -p ${PORT:-8000} tars_site.asgi:application"
