# Generated by Django 4.2.30 on 2026-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('repo', models.CharField(blank=True, max_length=500)),
                ('team_size', models.CharField(blank=True, choices=[('1', '1 — just me'), ('2-5', '2–5 engineers'), ('6-20', '6–20 engineers'), ('20+', '20+ engineers')], max_length=10)),
                ('use_case', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
